### ISSUE TITLE
The module cloudstack_sg_rule was not found in configured module paths

### ISSUE THREAD

**Issue by ngtuna** [runseb/ansible-kubernetes#9]
I ran `ansible-playbook k8s.yml` and got that

```
TASK [k8s : SSH for k8s] *******************************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "The module cloudstack_sg_rule was not found in configured module paths. Additionally, core modules are missing. If this is a checkout, run 'git submodule update --init --recursive' to correct this problem."}
    to retry, use: --limit @k8s.retry
```

**Comment by ngtuna** [comment]
pulled `ansible-cloudstack` submodule but no luck

**Comment by sebgoa** [comment]
ok that’s a leftover from the previous Ansible.

the module should not be something like:

cs_sgrule ? and not cloudstack_sg_rule

so this task needs to be modified:

https://github.com/skippbox/ansible-kubernetes/blob/ansible-cloudstack/roles/k8s/tasks/create_secgroup_rules.yml

**Comment by ngtuna** [comment]
That is.
